name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore src/JCL/JCL.csproj
      - name: Build
        run: dotnet build src/JCL/JCL.csproj -c Release --no-restore
      - name: Pack
        run: dotnet pack src/JCL/JCL.csproj -c Release --no-build -o ./artifacts
      - name: Publish to NuGet (if key)
        if: github.event_name == 'push'
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          if [ -n "${{ secrets.NUGET_API_KEY }}" ]; then
            dotnet nuget push ./artifacts/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
          else
            echo "No NUGET_API_KEY set; skipping push."
          fi
